trigger:
  branches:
    include:
      - main

variables:
  REGISTRY_NAME: project20registry
  IMAGE_NAME: aigeneration-service
  RESOURCE_GROUP: project20-rsrcgrp
  AKS_CLUSTER: project20-aks

stages:
- stage: BuildAndPush
  displayName: Build & Push Docker Image
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Checkout@1

  - task: AzureCLI@2
    name: loginACR
    inputs:
      azureSubscription: 'AzureServiceConnection' # 본인이 생성한 서비스 연결 이름
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr login --name $(REGISTRY_NAME)

  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      containerRegistry: '$(REGISTRY_NAME).azurecr.io'
      repository: '$(IMAGE_NAME)'
      command: buildAndPush
      Dockerfile: '**/Dockerfile'
      tags: |
        latest

- stage: DeployToAKS
  displayName: Deploy to AKS via kubectl
  dependsOn: BuildAndPush
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: AzureCLI@2
    name: setAKSContext
    inputs:
      azureSubscription: 'AzureServiceConnection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az aks get-credentials \
          --resource-group $(RESOURCE_GROUP) \
          --name $(AKS_CLUSTER) \
          --overwrite-existing

  - script: |
      kubectl set image deployment/aigeneration \
        aigeneration=$(REGISTRY_NAME).azurecr.io/$(IMAGE_NAME):latest
      kubectl rollout status deployment/aigeneration
    displayName: Update deployment image and rollout
