apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigeneration
  labels:
    app: aigeneration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aigeneration
  template:
    metadata:
      labels:
        app: aigeneration
    spec:
      containers:
        - name: aigeneration
          image: project20registry.azurecr.io/aigeneration-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
            - name: SPRING_PROFILES_ACTIVE
              value: default
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
